### ISSUE TITLE
Apple M1 ("Silicon") binary

### ISSUE THREAD

**Issue by eddelbuettel** [x13org/x13prebuilt#11]
As far as I understand it, the Fortran compiler situation is still in flux for the platform which should get settled either "soon" or "eventually" at which point we can look into a dedicated binary as a little bird tells that in @christophsax 's office such a precious chip is being present now ....

**Comment by christophsax** [comment]
@krlmlr is now using the M1 and is willing to have a look at it. 

My latest successful build for Mac Intel was done by this script: https://github.com/x13org/x13prebuilt/blob/build57/v1.1.57/mac/buildScript.sh

**Comment by krlmlr** [comment]
IIUC, the current situation is that it already works on the M1 Mac through the translation layer? I'll take a look.

The link no longer works for me, I'll take the script from the main branch.

**Comment by eddelbuettel** [comment]
Try https://github.com/x13org/x13prebuilt/blob/master/v1.1.57/mac/buildScript.sh -- @christophsax may have linked to the script while it was in a branch which, once merged and branch deleted, got stale.

The actual build can be pretty straightforward -- I did plain Linux and Linux-on-more-esoteric-armh7 this morning.  Essentially one call each to `wget`, `tar`, `make` and then `scp` (or `cp`) to keep the resulting binary...   On the mac I think it may need one or two adjustments for lowercase != UpperCase and other minor variants.  Plus of course the whole amazeball of not having an "officially blessed" Fortran compiler but you know more about all that than me ...
