### ISSUE TITLE
v1.1.57

### ISSUE THREAD

**Issue by christophsax** [x13org/x13prebuilt#12]
Census has a new website. That's why we missed Version 1.1, Build 57:

https://www.census.gov/data/software/x13as.X-13ARIMA-SEATS.html

**Update:** Some links are broken, but the files can be found here: https://www2.census.gov/software/x-13arima-seats/x13as/unix-linux/program-archives/ or https://www2.census.gov/software/x-13arima-seats/x13as/windows/program-archives/

I will start with my platforms (Mac and Win).

**Comment by eddelbuettel** [comment]
I can of course look into Linux.

**Comment by eddelbuettel** [comment]
I think with #16 by @krlmlr merged, we can close this as we have five new builds.
