### ISSUE TITLE
The new v1.1.57/mac/x13ashtml.tar.gz is not compressed

### ISSUE THREAD

**Issue by eddelbuettel** [x13org/x13prebuilt#14]
```sh
edd@rob:~/git/x13prebuilt/v1.1.57/mac(master)$ ls
buildScript.sh  README.md  x13ashtml.tar.gz
edd@rob:~/git/x13prebuilt/v1.1.57/mac(master)$ tar tvzf x13ashtml.tar.gz 

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
edd@rob:~/git/x13prebuilt/v1.1.57/mac(master)$ file x13ashtml.tar.gz 
x13ashtml.tar.gz: POSIX tar archive
edd@rob:~/git/x13prebuilt/v1.1.57/mac(master)$ tar tvf x13ashtml.tar.gz 
drwxr-xr-x christoph/wheel   0 2021-07-31 02:58 x13ashtml/
drwxr-xr-x christoph/wheel   0 2021-07-31 02:59 x13ashtml/bin/
drwxr-xr-x christoph/wheel   0 2021-07-31 03:03 x13ashtml/lib/
-rwxr-xr-x christoph/wheel 2810084 2021-07-31 03:03 x13ashtml/lib/libgfortran.5.dylib
-rwxr-xr-x christoph/wheel  288440 2021-07-31 03:03 x13ashtml/lib/libquadmath.0.dylib
-rw-r--r-- christoph/wheel  139704 2021-07-31 03:03 x13ashtml/lib/libgcc_s.1.dylib
-rwxr-xr-x christoph/wheel 4366228 2021-07-31 03:03 x13ashtml/bin/x13ashtml
edd@rob:~/git/x13prebuilt/v1.1.57/mac(master)$ 
```

I would suggets to _either_ actually compress the file, or just renamed it to end in `.tar` to signal that it is uncompressed.

~Also, shouldn't there be _two_ binaries for M1 and i7 ?~

**Comment by christophsax** [comment]
So I should just add a `z` to the options here?

https://github.com/x13org/x13prebuilt/blob/237a024efe80e9cb8374c7618e7e592596dc1682/v1.1.57/mac/buildScript.sh#L76

I haven't changed it, so this is probably what we always had.

M1 and i7: In the long-run, yes. For now, I think it is ok to proceed with the binaries as they are now. The intel binaries work fine and out-of-the-box on M1s, also in a native M1 R (according to my last tests, which are a few months old).

Kirill has now the M1 and tries to build them. I commented in https://github.com/x13org/x13prebuilt/issues/11. If he succeeds, we can add another folder.

**Comment by eddelbuettel** [comment]
I don't care which way you change it but calling an _un_compressed tarball `tar.gz` is about as truthful as calling it `.zip`

The previous note about M1 was too subtle for me to grasp that there was "optionality" here. I read it as "hold on for a few mins as there will be a binary".  There should be really nothing to compiling a folder of Fortran files into a binary, but I remain of course fully unware of the multitude of trap doors you get for all the money you pay for macOS releases :wink:.  I am sure you guys will figure it out.

**Comment by christophsax** [comment]
M1: Not minutes - days, perhaps months. No idea how or if the the trick with the fortran libraries works. Or how far the fortran compiler is for the platform.

But we will get there 😀
