### ISSUE TITLE
Various TODOs

### ISSUE THREAD

**Issue by eddelbuettel** [x13org/x13prebuilt#2]
We are mostly there, but there are a few things that had come to mind:
- [x] top-level README.md
- [x] README.md for Linux detailing build
- [x] README.md for OS X detailing build, maybe describing `install_name_tool` use
- [x] README.md for Windows

Possible extensions:
- [ ] Support for other Unix versions?  Building on top of the Linux build may do.  We probably need Solaris to really make CRAN happy, or else note that [x13binary](https://github.com/x13org/x13binary) is only for Linux, Windows. OS X
- [ ] Support for other OS X versions?  

_Edit 1_ Marked items 3 and 4 as done.

**Comment by christophsax** [comment]
- Will do the OS X and the Windows README. 
- Some years ago, I had Solaris installed for a few days, and was even running R there, I think. I could give it another try but it would take me some time. Meanwhile, we could do more testing on the other platforms.
- I try to find a computer with OS-X Mavericks (the other version tested on CRAN) and give it a run. Hope it will just work there as well.

**Comment by eddelbuettel** [comment]
Great!

Jeroen sometimes helps me with OS X issues---and he also has a Solaris machine (recovered from UCLA as I recall) somewhere.  We can help.   That said, it is a lot of files.  If it works, fine -- we'll support it -- but if not ... then maybe it is easier to wait for someone more motivated :)

**Comment by eddelbuettel** [comment]
Marked two items as done above.

**Comment by christophsax** [comment]
I have a OS-X Maverick's testing opportunity next Saturday (in a week).

**Comment by eddelbuettel** [comment]
I just cornered the ever-so-helpful @jeroenooms on this.  Solaris did not behave on his box.  

So we may need the plan B part of having x13binary fail gracefully on 'another OS' and seasonal also just static 'sorry, cannot work you' to motivate users to supply binaries and/or recipes.

**Comment by christophsax** [comment]
ok, shall I give it a try?

**Comment by eddelbuettel** [comment]
Sure!  I am supposed to work on something else but I'll gladly review.   

I guess we need to do two things:
1. Not have x13binary fail but just state it, maybe with a message that users could still manual insert in the `bin/` directory
2. Have seasonal complain but then not die so that Solaris doesn't actually fail.  Does that mean you have to `if/else` test all your functions?   Or at least the test functions?

**Comment by christophsax** [comment]
And because I am in a clean up mood: I thing our solution for Solaris is fine, and we have OS-X covered. So we can cancel the two possible extensions mentioned in the first post.
