### ISSUE TITLE
Update to Build 26

### ISSUE THREAD

**Issue by christophsax** [x13org/x13prebuilt#4]
Have built a new binary version for OS-X [here](https://github.com/x13org/x13prebuilt/tree/feature/built-26/v1.1.26/osx). 

Was thinking if  we shouldn't keep future versions in distinct locations (e.g., by putting it in a separate folder). A new version of x13binary would download it from the new location, so a specific version of x13binary would always use the same specific version of X-13. 
#### Changes in Build 26 (by Census)
- URL renamed to `.../x13ashtmlsrc_V1.1_B26.tar.gz`
- `makefile.g77` renamed to `makefile.gf`
- resulting binary file `x13ashtml` renamed to `x13asHTMLv11b26o1`
#### Tasks
- [X] Binary OS-X
- [x] Binary Linux
- [x] Binary Windows
- [x] update x13binary
- [x] test if seasonal works with new binaries

**Comment by eddelbuettel** [comment]
Lots of good ideas.  I think I am mostly nodding.   

I may have a beef with `makefile.gf`.  Why not just `Makefile`?  IIRC it worked just as well (with GNU make, which is more or less our default, no?)

The asHTML capitalization looks weird too.  Maybe x13ashtml.v11.b26.o1 or just use subdirectories?  Shouldn't matter too much either way...

**Comment by christophsax** [comment]
Ok, under "Changes in Build 26 (by Census)", I was just summarizing the changes _they_ did, I think we can keep these things as before. Main question was to have X-13-version specific URLs.

**Comment by eddelbuettel** [comment]
Doh. Silly me. Misread.

Keeping the URLs is certainly simpler and _probably_ good enough given the testing Census is doing.  Plus, we always have old binaries under version control...

**Comment by eddelbuettel** [comment]
I now added the `v1.1.26/` variants for 32 and 64 bit Linux, freshly compiled, and added an updated windows zip archive.

So we should be set.  Shall we move what have into `v1.1.19` or just overwrite?

**Comment by christophsax** [comment]
Great!

I have some preference not to overwrite. We could leave it as it is right now and move what we have into `v1.1.19` after we released a new x13binary (with adjusted URLs) on CRAN. So source installing x13binary from CRAN would continue to work as before for the moment. 

Meanwhile I can check out seasonal if it is affected by any of the changes.

**Comment by eddelbuettel** [comment]
I am still undecided.  Yes, 'it would still work' but it also implies we currently give them the outdated binaries.   If we just moved things around in x13prebuilt, we would _not_ have to update x13binary. Isn't that cleaner?

**Comment by christophsax** [comment]
For OS-X and Win, we would give them the outdated binaries anyway, via the CRAN binaries. So the binary and the source would be different, despite having the same version number? Also, I don't think it is cleaner to change the product but keep the version number the same.

But my main concern is that there may be some bigger changes on the Census side that require adjustments of seasonal. If build 26 is part of a new (development) version of of x13binary, we can do tests and adjustments in seasonal or wherever they are needed, and update only when everything works fine. When Census updated to build 19 a year ago, they added an additional statistic somewhere, which screwed up the `summary` method (christophsax/seasonal#88). There may be things like that in the present version as well.

A final point is that I could think of some people not wanting to upgrade to build 26, perhaps because they want get exactly the same results as before or because they did some extensive testing. They could still go for the older version of x13binary.

**Comment by eddelbuettel** [comment]
Ok, fair enough -- colour me convinced.

**Comment by christophsax** [comment]
I guess we can close this one.
